apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paas
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: gcr.io/containers-101/container-paas:broke
        ports:
        - containerPort: 5000
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "paas-lb"
  namespace: "default"
  labels:
    app: "web"
    tier: "frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "web"
    tier: "frontend"
  type: "LoadBalancer"
  loadBalancerIP: ""
