apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pets-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: web
        image: gcr.io/containers-101/container-pets
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: web
    tier: frontend
